# Form implementation generated from reading ui file 'dangnhap.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DangNhap(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(862, 398)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dkten = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.dkten.setGeometry(QtCore.QRect(380, 60, 171, 20))
        self.dkten.setObjectName("dkten")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(380, 20, 101, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 200, 191, 41))
        self.label_3.setObjectName("label_3")
        self.dnten = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.dnten.setGeometry(QtCore.QRect(380, 240, 171, 20))
        self.dnten.setObjectName("dnten")
        self.dkmk = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.dkmk.setGeometry(QtCore.QRect(380, 100, 171, 20))
        self.dkmk.setObjectName("dkmk")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 60, 181, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(190, 100, 101, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(190, 140, 191, 21))
        self.label_6.setObjectName("label_6")
        self.dknlmk = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.dknlmk.setGeometry(QtCore.QRect(380, 140, 171, 20))
        self.dknlmk.setObjectName("dknlmk")
        self.dnmk = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.dnmk.setGeometry(QtCore.QRect(380, 280, 171, 20))
        self.dnmk.setObjectName("dnmk")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 240, 181, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(190, 280, 101, 21))
        self.label_8.setObjectName("label_8")
        self.xacnhan1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.xacnhan1.setGeometry(QtCore.QRect(380, 170, 61, 21))
        self.xacnhan1.setObjectName("xacnhan1")
        self.xacnhan2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.xacnhan2.setGeometry(QtCore.QRect(380, 310, 61, 21))
        self.xacnhan2.setObjectName("xacnhan2")
        self.logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 151, 71))
        self.logo.setText("")
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 862, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Đăng ký</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Đăng Nhập</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Tên đăng nhập</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Mật khẩu</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Nhập Lại Mật Khẩu</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Tên đăng nhập</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Mật khẩu</span></p></body></html>"))
        self.xacnhan1.setText(_translate("MainWindow", "Xác Nhận"))
        self.xacnhan2.setText(_translate("MainWindow", "Xác Nhận"))
