# Form implementation generated from reading ui file 'trangchu.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TrangChu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 471)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 0, 341, 51))
        self.label.setObjectName("label")
        self.anh = QtWidgets.QLabel(parent=self.centralwidget)
        self.anh.setGeometry(QtCore.QRect(100, 120, 731, 301))
        self.anh.setText("")
        self.anh.setScaledContents(True)
        self.anh.setObjectName("anh")
        self.logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 91, 81))
        self.logo.setText("")
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.giohang = QtWidgets.QPushButton(parent=self.centralwidget)
        self.giohang.setGeometry(QtCore.QRect(580, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.giohang.setFont(font)
        self.giohang.setObjectName("giohang")
        self.sanpham = QtWidgets.QPushButton(parent=self.centralwidget)
        self.sanpham.setGeometry(QtCore.QRect(430, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sanpham.setFont(font)
        self.sanpham.setObjectName("sanpham")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(270, 50, 401, 31))
        self.textEdit.setObjectName("textEdit")
        self.trangchu = QtWidgets.QPushButton(parent=self.centralwidget)
        self.trangchu.setGeometry(QtCore.QRect(270, 50, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.trangchu.setFont(font)
        self.trangchu.setObjectName("trangchu")
        self.textEdit.raise_()
        self.label.raise_()
        self.anh.raise_()
        self.logo.raise_()
        self.giohang.raise_()
        self.sanpham.raise_()
        self.trangchu.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Shop Thời Trang NewGen</span></p></body></html>"))
        self.giohang.setText(_translate("MainWindow", "Giỏ Hàng"))
        self.sanpham.setText(_translate("MainWindow", "Sản Phẩm"))
        self.trangchu.setText(_translate("MainWindow", "Trang Chủ"))
